Repository datacarpentry/genomics-workshop, pull requests merged in 2023-09, with the labels that each got.

#145 Fix conditions under which Carpentries will set up AMI instances
  _extras/AMI-setup.md
Labels: type:instructor guide

#142 Update setup.md
  setup.md
Labels: type:typo text

#125 add miniconda3 linux installation instructions
  setup.md
Labels: type:enhancement
